# Snowflake -> GitHub sync workflow. 
name: Snowflake → Git DDL sync

on:
  workflow_dispatch:        
  #schedule:
  #  - cron: '0 3 * * *'     

permissions:
  contents: write

jobs:
  sync-ddls:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Snowflake → Git sync
        env:
          GH_APP_ID:         ${{ secrets.GH_APP_ID }}
          GH_INSTALLATION_ID:    ${{ secrets.GH_INSTALLATION_ID }}
          GH_PRIVATE_KEY_PATH:    ${{ secrets.GH_PRIVATE_KEY_PATH }}
          GH_REPOSITORY:    ${{ secrets.GH_REPOSITORY }}
        run: |
          python src.sync.py --source --commit
          